[server]
port = 80
address = "0.0.0.0"
# port = 8080
# address = "127.0.0.1"
headless = true
# enableWebsocketCompression = false
# enableCORS = false
# maxExecutionTime = 1800
# maxUploadSize = 1024

[browser]
gatherUsageStats = false

[theme]
# base = "light"
base = "dark"